version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./Frontend
    ports:
      - 3001:3000

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mongo
      - frontend
      - backend
    

volumes:
  mongo_data:
