version: '3.8'
services:
  backend:
    image: backend-exemple
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  frontend:
    image: frontend-exe
    ports:
      - 5000:5000
    depends_on:
      - db 
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      
    container_name: database08
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - frontend
      - backend
    

    