version: '3.8'

services:
  backend:
    image: backend-exemple
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  frontend:
    image: frontend-exe
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis

    